version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: crm_php_app
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: crm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: kevin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
